# Testing Review

## Tests Reviewed

- **Test Source File:** [/testing/reviews/test_is_valid_email_in_database.py]
  - **Test Function Name:** `test_is_valid_email_in_database`
    - **Date Reviewed:** 08/09/2023
    - **Comments:**
      - The test appears to fail when I run it from pytest due to an operational error. It is unabble to open database file. I'm not sure if it's just from my end.



- **Test Source File:** [/testing/reviews/update_password.py]
  - **Test Function Name:** `update_password.py`
    - **Date Reviewed:** 08/09/2023
    - **Comments:**
      - The test appears to fail again when I run it from pytest due to an operational error. It is unabble to open database file. Again, I'm not sure if it's just from my end.


- **Test Source File:** [/testing/reviews/test_inventory.py]
  - **Test Function Name:** `test_inventory.py`
    - **Date Reviewed:** 08/09/2023
    - **Comments:**
      - The test appears to fail again when I run it from pytest due 1 error collecting test_inventory.py. Maybe it is because the test module doesn't have a valid python name.
